name: form_builder_phone_field
description: International phone number field for FlutterFormBuilder package
version: 3.0.1
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/issues
homepage: https://github.com/flutter-form-builder-ecosystem
topics: 
  - form
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.3.0+1
  country_pickers: ^3.0.1
  phone_numbers_parser: ^9.0.19

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
