name: form_builder_phone_field
description: International phone number field for FlutterFormBuilder package
version: 1.1.0
homepage: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.3.1
  phone_number: ^0.12.0+2
  country_pickers: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
